version: "3.8"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/nestJs/src/app
      - ./nestJs/src/app/node_modules
    command: npm run start:dev
    depends_on: 
      - postgres
    environment: 
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      JWT_SECRET: SecretPassword123
      PORT: 8000
    ports:
      - 8000:8000
      - 9229:9229
  mongodb:
      image: 'mongo'
      ports:
        - "27017:27017"
      restart: always
      volumes:
        - ./mongo-data:/data/db

  postgres:
    image: postgres:10.4
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 8080:5432

